# ============================== Filebeat inputs ===============================
filebeat.inputs:
- type: log
  enabled: true
  tags:
    - app_1_pm2
  paths:
    - /usr/share/filebeat/services/node/*.log

# ============================== Filebeat modules ==============================
filebeat.config.modules:
  enabled: true
  path: ${path.config}/modules.d/*.yml

# =============================== Kibana output ==================================

# output.logstash:
#   hosts: ["logstash:5044"]

output.kafka:
  hosts: ["kafka:19092"]
  topic: "applogs"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

# ================================= Logging =====================================
logging.level: info
